### ISSUE TITLE
Styling Conventions Guidelines

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#7]
The new "[`CONVENTIONS.md`][CONVENTIONS]" document contains the _Formatting and Styling Conventions_ guidelines adopted in Alan-Docs.

This Issue tracks the status of the guidelines, as there are still many points not convered by the document (although already discussed in [Issues]). It also provides a thread for discussion on the topic of styling convention across Alan documentation.

- [ ] Alan Code
    + [x] Code Examples Blocks (see Issue #2)
        * [x] keywords casing
        * [x] predefined classes casing
        * [x] code truncation (`...`)
    + [ ] Inline code (see Issue #1)
- [ ] BNF Definitions (see Issue #2)
- [ ] Game Transcipts
- [ ] Player input (inline)
    + [ ] `ALL` and `AND` player input (where AND is not to be confused with the Alan keyword)

-------------------------------------------------------------------------------

All Issues on the topic are labelled as "[`styling conventions`][Issues]".

[CONVENTIONS]: https://github.com//alan-if/alan-docs/blob/master/CONVENTIONS.md "Read the 'Formatting and Styling Conventions' guidelines adopted in Alan-Docs"

[Issues]: https://github.com/alan-if/alan-docs/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22styling+conventions%22+ "View all Issues on 'syling conventions'"
