### ISSUE TITLE
*** FINAL TASKS FOR BETA7 RELEASE ***

### ISSUE THREAD

**Issue by tajmone** [alan-if/alan-docs#75]
This Issue will be constantly updated, pointing out the pending tasks that need to be attended.

-------------------------------------------------------------------------------

## Urgent Tasks

Issues or PRs that require **immediate** attention (as in: _by yesterday_ :wink:).

- [x] #35 ("Manual on Verb Qualifiers") — @thoni56: there seem to be contradicting statements in §3.11, about VERB execution order (`DOES [BEFORE|ONLY|AFTER]`). _VERBs_. It might be worth fixing this "bug", for it affects understanding correctly how VERBs work.
- [x] #25 ("TBDs in App. G: Keep or Comment Out?") — @thoni56: it's just about deciding whether we should keep the "TO BE DONE" notices in those in-the-working chapters, or if temporarily comment out the whole section (title included), before the official release.
- [x] #41 ("Check Manual on Alan/ARun Switches") — @tajmone: just verify that the `alan` and `arun` switches mirror the current state of the Beta7 SDK release.

-------------------------------------------------------------------------------

## Valuable Tasks

Issues or PRs that only require minor efforts to be solved.

- [x] #8 ("Manual Info & Metadata") — @tajmone: worth adding the metadata before Beta7 release, shouldn't take long.
- [x] #63 ("Pending Glossary Entries") — not mandatory, but since there's only a single glossary entry right now, it might be worth adding a couple more, for completness sake.
- [x] #74 ("ALAN Manual 1st Release ETA") — @tajmone & @thoni56: discussing the final details to plan the release, like merge/squash strategy, pre-release checklist, and all other :japanese_ogre:  nitty gritty gory details :japanese_ogre:. 

-------------------------------------------------------------------------------

## That's It, Really...

The above pending Issues are the last ones in the "mandatory list" before the Beta7 release of the _Manual_. So, handled those we only need to do some cleanup (e.g. checking that the version info of both the _Manual_ and the ALAN SDK are correct, etc.,), and decide how to publish (merge vs squash), and other nitty gritty — to be dealt with in #74.

The rest of the pending improvements are listed in the [`Alan Manual (dev)` project][proj Man dev], but none of them are preventing the first release of the book.

[proj Man dev]: https://github.com/alan-if/alan-docs/projects/6
